# Generated by Django 5.1 on 2024-09-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='type',
            field=models.CharField(blank=True, choices=[('factory', 'завод'), ('retail network', 'розничная сеть'), ('sole proprietor', 'индивидуальный предприниматель')], max_length=100, null=True, verbose_name='Тип производителя'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Задолженность перед поставщиком'),
        ),
    ]
